#!/usr/bin/env bash
# filter-review-diff.sh — Strip unreviewable bytes from a unified diff before
# any review model reads them.
#
# No model can meaningfully assess a lockfile hunk, minified/sourcemap
# output, or vendored code — on a mixed PR they are pure input cost for
# every review dimension. This filters them out deterministically, before
# context assembly, so both the small-PR (full diff) and large-PR (per-file
# diff) paths in SKILL.md step 2 share one definition of "generated".
#
# Usage:
#   filter-review-diff.sh [summary-file] < unified-diff > filtered-diff
#
#   $1 (optional) — path to write the exclusion summary to. One line per
#                   stripped file: "<path>  +<adds>/-<dels>  <reason>".
#                   Defaults to /dev/null (summary discarded). The summary
#                   is NEVER written to stdout — callers that need it must
#                   pass a real file.
#
# Classification (per `diff --git a/X b/X` section), in priority order:
#   1. EXEMPT (always kept, beats every rule below): path has a
#      "migrations" or "migrate" directory component.
#   2. STRIP: path is a well-known dependency lockfile (self-contained
#      list in classify_path below), or is `*.min.js` / `*.min.css` /
#      `*.map`, or sits under a `vendor/`, `node_modules/`, or
#      `third_party/` path segment.
#   3. STRIP: the path looks generated (protobuf/codegen suffixes, or a
#      generated/, dist/, or build/ path segment — see classify_path)
#      AND a generated-content marker (`@generated`, the Go
#      "Code generated ... DO NOT EDIT." line, or protoc's "Generated by
#      the protocol buffer compiler. DO NOT EDIT!") appears in one of
#      the section's first 5 ADDED lines or on any context line within
#      the bounded buffering window. Markers only in REMOVED lines do
#      not strip (the file is leaving, not arriving, generated), and a
#      marker on a non-generated-looking path never strips — an
#      author-planted marker cannot hide an ordinary file from review.
#   4. Otherwise: kept, byte-identical.
#
# Sections are detected at `diff --git` headers; input with no such
# headers where sections start directly at `--- a/X` (the GitLab MR
# diff shape) is handled too — see the gitlab_mode transitions below.
#
# Bash 3.2 compatible (macOS ships 3.2 — no associative arrays, no
# ${var,,}). The classifier itself is a single awk program reading stdin
# one line at a time: a multi-thousand-line lockfile hunk is never
# buffered whole, in awk or in a shell variable. The only lines ever held
# in memory are one file-section's header lines, plus (for sections that
# are not fast-path classified by path) content lines up to the 5-added-
# line @generated check — capped at 100 buffered lines per section, so a
# deletion-only section never buffers whole.
#
# Malformed input (neither `diff --git` nor `--- a/` section markers,
# or a section this parser can't make sense of) passes through unchanged
# rather than erroring: the failure mode here must be an unfiltered
# review, never a broken one.
set -euo pipefail

SUMMARY_FILE="${1:-/dev/null}"

# Truncate up front: a no-exclusions run must leave an empty summary, not
# a previous run's stale one. Harmless no-op on /dev/null.
: > "${SUMMARY_FILE}"

# LC_ALL=C pins byte semantics: sprintf("%c", n) in dequote() must emit
# the raw byte (gawk in a UTF-8 locale would emit a multi-byte
# character), and regex matching stays byte-safe on arbitrary path bytes.
LC_ALL=C awk -v summary_file="${SUMMARY_FILE}" '
function reset_section() {
  path = ""; old_path = ""; new_path = ""
  hdr_old = ""; hdr_new = ""
  phase = "header"      # header -> pending -> keep|strip
  reason = ""
  added_seen = 0
  generated_hit = 0
  sec_adds = 0
  sec_dels = 0
  buf_n = 0
}

# Index of the closing quote of the git-quoted string starting at
# position 1 of s, or 0 if unterminated.
function quote_end(s,   i, c) {
  for (i = 2; i <= length(s); i++) {
    c = substr(s, i, 1)
    if (c == "\\") i++
    else if (c == "\"") return i
  }
  return 0
}

# Undoes git path quoting: strips the surrounding double quotes, the \"
# and \\ escapes, and decodes octal escapes (\303\251 -> the raw UTF-8
# bytes) so summary paths match the changed-file list byte-for-byte.
# Control escapes (\t \n \r) stay literal backslash sequences — the
# exclusion summary must remain one physical line per record, so a \n
# in a filename must never become a real newline.
function dequote(s,   out, i, c, n, j) {
  s = substr(s, 2, length(s) - 2)
  out = ""
  for (i = 1; i <= length(s); i++) {
    c = substr(s, i, 1)
    if (c == "\\" && i < length(s)) {
      c = substr(s, i + 1, 1)
      if (c == "\"" || c == "\\") { out = out c; i++; continue }
      if (c >= "0" && c <= "7") {
        n = 0
        for (j = 0; j < 3 && i < length(s); j++) {
          c = substr(s, i + 1, 1)
          if (c < "0" || c > "7") break
          n = n * 8 + c
          i++
        }
        out = out sprintf("%c", n)
        continue
      }
      c = "\\"
    }
    out = out c
  }
  return out
}

# Rename metadata paths carry no a/ b/ prefix but may be git-quoted.
# Undecodable quoting returns "" so section_path() falls back to the
# diff --git header path.
function rename_path(s,   i) {
  if (substr(s, 1, 1) != "\"") return s
  i = quote_end(s)
  if (i == 0) return ""
  return dequote(substr(s, 1, i))
}

# Path extraction from `--- `/`+++ ` header lines. Git terminates the
# path with a tab when it contains spaces — strip from the first tab so
# $-anchored rules still match. The a/ b/ prefix is required; /dev/null
# and quoted paths leave the variable unset (the diff --git header
# fallback covers those).
function set_old_path(line,   p) {
  p = substr(line, 5)
  sub(/\t.*$/, "", p)
  if (p != "/dev/null" && substr(p, 1, 2) == "a/") old_path = substr(p, 3)
}

function set_new_path(line,   p) {
  p = substr(line, 5)
  sub(/\t.*$/, "", p)
  if (p != "/dev/null" && substr(p, 1, 2) == "b/") new_path = substr(p, 3)
}

# Position of the last occurrence of t in s, or 0.
function last_index(s, t,   i, p) {
  p = 0
  for (i = index(s, t); i > 0; i = index(substr(s, p + 1), t)) p += i
  return p
}

# Best-effort old/new paths from the `diff --git a/X b/Y` header line
# itself — the only header a binary or mode-only section is guaranteed
# to carry, and the fallback when the ---/+++ paths are git-quoted.
# Leaves hdr_old/hdr_new empty when the line cannot be split (an
# unparsed section fails open at classification time).
function parse_git_header(line,   rest, i, p, cut, matched) {
  rest = substr(line, 12)
  if (substr(rest, 1, 1) == "\"") {
    i = quote_end(rest)
    if (i == 0 || substr(rest, i + 1, 1) != " ") return
    if (substr(rest, 2, 2) == "a/") hdr_old = substr(dequote(substr(rest, 1, i)), 3)
    rest = substr(rest, i + 2)
  } else {
    # An unquoted path may itself contain spaces — even " b/". Prefer
    # the split where both sides name the same file (the overwhelmingly
    # common non-rename case); otherwise fall back to the last " b/"
    # (or quoted: " \"b/) marker on the line.
    matched = 0
    cut = 0
    p = 0
    for (i = index(rest, " b/"); i > 0; i = index(substr(rest, p + 1), " b/")) {
      p += i
      cut = p
      if (substr(rest, 3, p - 3) == substr(rest, p + 3)) { matched = 1; break }
    }
    if (!matched) {
      i = last_index(rest, " \"b/")
      if (i > cut) cut = i
    }
    if (cut == 0) return
    if (substr(rest, 1, 2) == "a/") hdr_old = substr(rest, 3, cut - 3)
    rest = substr(rest, cut + 1)
  }
  if (substr(rest, 1, 1) == "\"") {
    i = quote_end(rest)
    if (i == 0) return
    rest = dequote(substr(rest, 1, i))
  }
  if (substr(rest, 1, 2) == "b/") hdr_new = substr(rest, 3)
}

# The path a section is classified by: ---/+++ (or rename) headers
# first, the diff --git header as fallback. Empty means unparseable.
function section_path() {
  if (new_path != "") return new_path
  if (old_path != "") return old_path
  if (hdr_new != "") return hdr_new
  return hdr_old
}

# Content markers that identify generated output: the @generated
# convention, the canonical Go marker (golang.org/s/generatedcode), and
# the protocol buffer compiler header. `text` is the line without its
# leading +/space diff character.
function has_generated_marker(text) {
  if (index(text, "@generated") > 0) return 1
  if (text ~ /^\/\/ Code generated .* DO NOT EDIT\.$/) return 1
  if (index(text, "Generated by the protocol buffer compiler. DO NOT EDIT!") > 0) return 1
  return 0
}

# Classifies the current `path` into phase=keep|strip(+reason)|pending.
# pending means: not exempt, not a fast-path strip, but the path looks
# generated — still need the bounded content-marker check before a
# final call can be made.
function classify_path(   lp) {
  if (path ~ /(^|\/)(migrations|migrate)\//) {
    phase = "keep"
    return
  }
  lp = tolower(path)
  # Well-known dependency lockfiles across ecosystems (npm, yarn, pnpm,
  # Go, Rust, Ruby, Python, PHP).
  if (lp ~ /(^|\/)(package-lock\.json|yarn\.lock|pnpm-lock\.yaml|npm-shrinkwrap\.json|go\.sum|cargo\.lock|gemfile\.lock|poetry\.lock|composer\.lock)$/) {
    phase = "strip"; reason = "lockfile"; return
  }
  if (path ~ /\.min\.(js|css)$/) {
    phase = "strip"; reason = "minified"; return
  }
  if (path ~ /\.map$/) {
    phase = "strip"; reason = "sourcemap"; return
  }
  if (path ~ /(^|\/)(vendor|node_modules|third_party)\//) {
    phase = "strip"; reason = "vendored"; return
  }
  # Content-marker stripping is gated on generated-looking paths: an
  # author-planted @generated in an ordinary source file must not hide
  # it from review. Deliberately tight list: protoc outputs (.pb.go,
  # _pb2.py*), codegen suffixes (.gen.go, _generated.*), and
  # generated/, dist/, build/ path components. Anything else is kept
  # without a content check.
  if (lp ~ /\.pb\.go$|\.gen\.go$|_pb2\.py|_generated\.|(^|\/)(generated|dist|build)\//) {
    phase = "pending"
    return
  }
  phase = "keep"
}

function flush_buf(   i) {
  for (i = 1; i <= buf_n; i++) print buf[i]
  buf_n = 0
}

# Emits the one-line exclusion-summary record for the section that just
# finished being classified "strip". Never touches stdout.
function emit_summary() {
  print path "  +" sec_adds "/-" sec_dels "  " reason > summary_file
}

# Called when a section closes (next "diff --git" line, or EOF) to settle
# any decision that was left open while streaming.
function finalize_section() {
  if (phase == "strip") {
    emit_summary()
  } else if (phase == "pending") {
    # Section ended before 5 added lines ever appeared (small change, or a
    # deletion-heavy diff) - decide from whatever the first <5 held.
    if (generated_hit) { reason = "generated-marker"; emit_summary() }
    else { flush_buf() }
  } else if (phase == "header") {
    # No hunk and no "Binary files" line ever appeared: a pure rename or
    # mode-only change with no content diff at all. Classify from
    # whichever path we captured.
    path = section_path()
    if (path == "") { flush_buf(); return }
    classify_path()
    if (phase == "strip") { buf_n = 0; emit_summary() }
    else { flush_buf() }
  }
  # phase == "keep": already streamed directly, buffer is already empty.
}

# A possible GitLab section boundary: a `--- ` path line seen where a
# new section could start. Only a candidate — a REMOVED content line
# whose original text begins "-- a/..." produces exactly the same
# bytes, so the boundary is confirmed only when the very next line is
# the paired `+++ ` header (one-line lookahead in the main block).
function is_gl_candidate(line) {
  if (line !~ /^--- (a\/|"a\/)/ && line != "--- /dev/null") return 0
  if (!in_diff) return 1
  return gitlab_mode && phase != "header"
}

# One input line through the full state machine. Factored into a
# function so the GitLab-boundary lookahead in the main block can
# replay a rejected candidate line through the exact same logic.
function process(line,   c) {
  if (!in_diff) {
    if (line ~ /^diff --git /) {
      in_diff = 1
      buf[++buf_n] = line
      parse_git_header(line)
      return
    }
    print line
    return
  }

  if (line ~ /^diff --git /) {
    finalize_section()
    reset_section()
    buf[++buf_n] = line
    parse_git_header(line)
    return
  }

  if (phase == "keep") {
    print line
    return
  }

  if (phase == "strip") {
    c = substr(line, 1, 1)
    if (c == "+") sec_adds++
    else if (c == "-") sec_dels++
    return
  }

  if (phase == "header") {
    if (line ~ /^--- /) {
      set_old_path(line)
      buf[++buf_n] = line
      return
    }
    if (line ~ /^\+\+\+ /) {
      set_new_path(line)
      buf[++buf_n] = line
      return
    }
    if (line ~ /^rename to /) {
      if (new_path == "") new_path = rename_path(substr(line, 11))
      buf[++buf_n] = line
      return
    }
    if (line ~ /^rename from /) {
      if (old_path == "") old_path = rename_path(substr(line, 13))
      buf[++buf_n] = line
      return
    }
    if (line ~ /^@@ / || line ~ /^Binary files /) {
      buf[++buf_n] = line
      path = section_path()
      if (path == "") {
        # Fail-open: no path parsed from any header — never classify
        # (much less strip) a section this parser cannot even name.
        phase = "keep"; flush_buf(); return
      }
      classify_path()
      if (phase == "keep") { flush_buf(); return }
      if (phase == "strip") { buf_n = 0; return }
      return   # phase == "pending": keep buffering into the content below
    }
    buf[++buf_n] = line
    return
  }

  # phase == "pending": buffering, watching the first 5 added lines and
  # every context line for a generated-content marker. The decision
  # resolves at the 5th added line or the 100th buffered line, whichever
  # comes first, so a deletion-only or low-addition section never
  # buffers unbounded.
  buf[++buf_n] = line
  c = substr(line, 1, 1)
  if (c == "+") {
    sec_adds++
    if (added_seen < 5) {
      added_seen++
      if (has_generated_marker(substr(line, 2))) generated_hit = 1
    }
  } else if (c == "-") {
    sec_dels++
  } else if (c == " ") {
    # Context lines carry the marker when a generated file is modified
    # rather than added.
    if (has_generated_marker(substr(line, 2))) generated_hit = 1
  }
  if (added_seen >= 5 || buf_n >= 100) {
    if (generated_hit) { reason = "generated-marker"; phase = "strip"; buf_n = 0 }
    else { phase = "keep"; flush_buf() }
  }
}

BEGIN { in_diff = 0; gitlab_mode = 0; gl_cand = ""; reset_section() }

{
  if (gl_cand != "") {
    cand = gl_cand
    gl_cand = ""
    if ($0 ~ /^\+\+\+ /) {
      # Confirmed GitLab section boundary: the ---/+++ pair. GitLab MR
      # diffs carry no `diff --git` headers — sections start here.
      if (in_diff) finalize_section()
      reset_section()
      in_diff = 1
      gitlab_mode = 1
      set_old_path(cand)
      buf[++buf_n] = cand
      process($0)
      next
    }
    # Not a boundary: the candidate was ordinary content — replay it.
    process(cand)
  }
  if (is_gl_candidate($0)) {
    gl_cand = $0
    next
  }
  process($0)
  next
}

END {
  if (gl_cand != "") process(gl_cand)
  if (in_diff) finalize_section()
}
'
