#!/usr/bin/env python3
"""Compose child-issue markdown for create-children.sh.

Visible by default (inside Jira Description): Scope / proposal / AC.
Collapsed via markdown-to-adf --wrap-detail: "## Detailed Specification".

Does not re-append Acceptance Criteria when the description already has that section.
"""
from __future__ import annotations

import re
import sys

MAX_INPUT_BYTES = 2_000_000


def compose(desc: str, ac_md: str, priority_text: str, scope: str) -> str:
    # Promote first thematic break before detail sections into an explicit heading
    # so --wrap-detail collapses only that block (not ad-hoc HRs).
    desc = re.sub(
        r"(?m)^---\s*\n(?=\s*## (?:Requirements|Dependencies|Background|"
        r"Non-Functional|Use Cases|NFRs)\b)",
        "## Detailed Specification\n\n",
        desc,
        count=1,
    )

    # Normalize prose "Acceptance Criteria:" into a real heading for scannability.
    desc = re.sub(
        r"(?im)^Acceptance Criteria:\s*$",
        "## Acceptance Criteria",
        desc,
        count=1,
    )

    has_ac = bool(
        re.search(r"(?im)^#{1,4}\s*Acceptance Criteria\b", desc)
        or re.search(r"(?im)^Acceptance Criteria:\s*\n\s*[-*]", desc)
    )

    parts = [desc.rstrip()]
    if ac_md.strip() and not has_ac:
        parts.append("\n\n## Acceptance Criteria\n\n" + ac_md.strip())

    # Trailing rule + footer: wrap-detail peels generator footers back out of expand.
    parts.append(
        "\n\n---\n"
        f"*Priority: {priority_text} | Scope: {scope} | "
        "Generated by fullsend refine agent*"
    )
    return "\n".join(parts).strip() + "\n"


def main() -> int:
    if len(sys.argv) != 5:
        print(
            "usage: compose-child-markdown.py DESC AC_MD PRIORITY SCOPE",
            file=sys.stderr,
        )
        return 2
    desc, ac_md, priority_text, scope = sys.argv[1:5]
    if len(desc) > MAX_INPUT_BYTES:
        print("ERROR: description too large", file=sys.stderr)
        return 1
    sys.stdout.write(compose(desc, ac_md, priority_text, scope))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
