#!/usr/bin/env bash
# example-link-check-test.sh — Tests for examples/link-check/scripts/post-link-check.sh
#
# The example agent under examples/ is generated by `fullsend agent new` and
# is meant to be copied, so its post-script has to hold up to the same
# scrutiny as a fleet one: it consumes untrusted model output and turns it
# into a comment on a work item.
#
# Run from the repo root:
#   bash scripts/example-link-check-test.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
POST_SCRIPT="${REPO_ROOT}/examples/link-check/scripts/post-link-check.sh"

FAILURES=0

pass() { echo "PASS: $1"; }
fail() { echo "FAIL: $1 — $2"; FAILURES=$((FAILURES + 1)); }

# run_post <result-json> [env assignments...]
# Runs the post-script the way fullsend runs it: the working directory is the
# RUN directory and the agent's output lives in iteration-<N>/output/, per
# `postCmd.Dir = runDir` in internal/cli/run.go. Always in dry-run mode, so
# nothing is ever posted.
run_post() {
  local result_json="$1"; shift
  local workdir
  workdir="$(mktemp -d)"
  mkdir -p "${workdir}/iteration-1/output"
  printf '%s' "${result_json}" > "${workdir}/iteration-1/output/agent-result.json"

  local rc=0
  ( cd "${workdir}" \
      && ISSUE_URL="${ISSUE_URL_OVERRIDE:-https://github.com/fullsend-ai/demo/pull/99}" \
         GH_TOKEN="test-token" \
         POST_LINK_CHECK_DRY_RUN=1 \
         "$@" \
         bash "${POST_SCRIPT}" ) > "${workdir}/stdout" 2> "${workdir}/stderr" || rc=$?
  LAST_STDOUT="$(cat "${workdir}/stdout")"
  LAST_STDERR="$(cat "${workdir}/stderr")"
  rm -rf "${workdir}"
  return "${rc}"
}

# --- The script exists and is executable ---

if [[ -x "${POST_SCRIPT}" ]]; then
  pass "post-script-is-executable"
else
  fail "post-script-is-executable" "${POST_SCRIPT} is missing or not executable"
fi

# --- Happy path: findings are posted ---

if run_post '{"status":"findings","summary":"2 broken links","comment":"- a.md -> missing.md"}'; then
  if [[ "${LAST_STDOUT}" == *"2 broken links"* && "${LAST_STDOUT}" == *"a.md"* ]]; then
    pass "findings-are-rendered"
  else
    fail "findings-are-rendered" "summary or comment missing from output: ${LAST_STDOUT}"
  fi
else
  fail "findings-are-rendered" "script exited non-zero"
fi

# --- status ok posts nothing ---

if run_post '{"status":"ok","summary":"all good","comment":"All documentation links resolve."}'; then
  if [[ "${LAST_STDERR}" == *"nothing to post"* ]]; then
    pass "ok-status-posts-nothing"
  else
    fail "ok-status-posts-nothing" "expected a 'nothing to post' notice, got: ${LAST_STDERR}"
  fi
else
  fail "ok-status-posts-nothing" "script exited non-zero"
fi

# --- Rejected inputs: each must fail rather than post ---

assert_rejected() {
  local name="$1" json="$2" expect="$3"
  if run_post "${json}"; then
    fail "${name}" "script accepted input it should reject"
  elif [[ "${LAST_STDERR}" == *"${expect}"* ]]; then
    pass "${name}"
  else
    fail "${name}" "wrong error; wanted '${expect}', got: ${LAST_STDERR}"
  fi
}

assert_rejected "rejects-invalid-json" 'not json at all' "is not a JSON object"
# `jq -e .` used to be the gate: it reports a bare null/false document as
# invalid JSON, and lets a top-level array through to a raw jq error under
# set -e. All three must now be refused as "not a JSON object".
assert_rejected "rejects-bare-null" 'null' "is not a JSON object"
assert_rejected "rejects-bare-false" 'false' "is not a JSON object"
assert_rejected "rejects-top-level-array" '[{"status":"ok"}]' "is not a JSON object"
assert_rejected "rejects-multiline-summary" \
  '{"status":"findings","summary":"line one\nline two","comment":"c"}' \
  "summary must be a single line"
assert_rejected "rejects-unknown-status" '{"status":"explode","summary":"s","comment":"c"}' "status must be"
assert_rejected "rejects-missing-summary" '{"status":"findings","comment":"c"}' "summary is required"
assert_rejected "rejects-missing-comment" '{"status":"findings","summary":"s"}' "comment is required"

# A non-string field must be ignored by the allowlist, not coerced. jq's
# type guard turns it into an empty value, which then fails the required check.
assert_rejected "rejects-non-string-summary" \
  '{"status":"findings","summary":{"nested":true},"comment":"c"}' "summary is required"
assert_rejected "rejects-non-string-status" \
  '{"status":["findings"],"summary":"s","comment":"c"}' "status must be"

# Over-long summary is refused rather than silently truncated.
LONG_SUMMARY="$(printf 'x%.0s' $(seq 1 201))"
assert_rejected "rejects-over-long-summary" \
  "{\"status\":\"findings\",\"summary\":\"${LONG_SUMMARY}\",\"comment\":\"c\"}" \
  "summary exceeds"

# --- ISSUE_URL is validated, not trusted ---

for bad_url in \
  "https://evil.example.com/fullsend-ai/demo/pull/99" \
  "https://github.com/fullsend-ai/demo/pull/99/../../x" \
  "not-a-url"
do
  ISSUE_URL_OVERRIDE="${bad_url}" \
    assert_rejected "rejects-issue-url:${bad_url}" \
      '{"status":"findings","summary":"s","comment":"c"}' \
      "not a GitHub issue or pull request URL"
done
unset ISSUE_URL_OVERRIDE

# --- An over-long comment is truncated, not rejected ---

LONG_COMMENT="$(printf 'y%.0s' $(seq 1 17000))"
if run_post "{\"status\":\"findings\",\"summary\":\"s\",\"comment\":\"${LONG_COMMENT}\"}"; then
  if [[ "${LAST_STDOUT}" == *"(truncated)"* ]]; then
    pass "truncates-over-long-comment"
  else
    fail "truncates-over-long-comment" "expected a truncation marker"
  fi
  # The marker must fit INSIDE the cap, not extend past it: cutting at
  # MAX_COMMENT_CHARS and then appending would overshoot the limit the
  # result schema declares.
  body_len=$(printf '%s' "${LAST_STDOUT}" | tail -n +3 | wc -c | tr -d ' ')
  if (( body_len <= 16384 )); then
    pass "truncated-comment-stays-within-the-cap"
  else
    fail "truncated-comment-stays-within-the-cap" "comment body is ${body_len} chars, cap is 16384"
  fi
else
  fail "truncates-over-long-comment" "script exited non-zero"
fi

# --- Missing result file ---

workdir="$(mktemp -d)"
rc=0
( cd "${workdir}" && ISSUE_URL="https://github.com/fullsend-ai/demo/pull/99" \
    GH_TOKEN=t POST_LINK_CHECK_DRY_RUN=1 bash "${POST_SCRIPT}" ) >/dev/null 2>"${workdir}/err" || rc=$?
if [[ "${rc}" -ne 0 ]] && grep -q "no agent-result.json found" "${workdir}/err"; then
  pass "rejects-missing-result-file"
else
  fail "rejects-missing-result-file" "expected a not-found failure, got: $(cat "${workdir}/err")"
fi
rm -rf "${workdir}"

# --- Later iterations win, and a validated iteration wins over both ---

workdir="$(mktemp -d)"
for n in 1 2; do
  mkdir -p "${workdir}/iteration-${n}/output"
  printf '{"status":"findings","summary":"iteration %s","comment":"c"}' "${n}" \
    > "${workdir}/iteration-${n}/output/agent-result.json"
done
out=$( cd "${workdir}" && ISSUE_URL="https://github.com/fullsend-ai/demo/pull/99" \
    GH_TOKEN=t POST_LINK_CHECK_DRY_RUN=1 bash "${POST_SCRIPT}" 2>/dev/null )
if [[ "${out}" == *"iteration 2"* ]]; then
  pass "uses-the-last-iteration"
else
  fail "uses-the-last-iteration" "expected iteration 2, got: ${out}"
fi

# FULLSEND_VALIDATED_ITERATION_DIR names the iteration that passed validation,
# which is not necessarily the last one, so it must win over the scan.
out=$( cd "${workdir}" && ISSUE_URL="https://github.com/fullsend-ai/demo/pull/99" \
    GH_TOKEN=t POST_LINK_CHECK_DRY_RUN=1 \
    FULLSEND_VALIDATED_ITERATION_DIR="${workdir}/iteration-1/output" \
    bash "${POST_SCRIPT}" 2>/dev/null )
if [[ "${out}" == *"iteration 1"* ]]; then
  pass "validated-iteration-wins"
else
  fail "validated-iteration-wins" "expected iteration 1, got: ${out}"
fi
rm -rf "${workdir}"

# --- Required environment ---

workdir="$(mktemp -d)"
mkdir -p "${workdir}/iteration-1/output"
echo '{}' > "${workdir}/iteration-1/output/agent-result.json"
rc=0
( cd "${workdir}" && env -u ISSUE_URL GH_TOKEN=t bash "${POST_SCRIPT}" ) >/dev/null 2>&1 || rc=$?
if [[ "${rc}" -ne 0 ]]; then
  pass "requires-issue-url"
else
  fail "requires-issue-url" "script ran without ISSUE_URL"
fi
rm -rf "${workdir}"

if [[ "${FAILURES}" -gt 0 ]]; then
  echo "${FAILURES} test(s) failed"
  exit 1
fi
echo "All tests passed"
