#!/usr/bin/env bash
# filter-review-diff-test.sh — Tests for
# skills/pr-review/scripts/filter-review-diff.sh
#
# Run from the repo root:
#   bash scripts/filter-review-diff-test.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FILTER="${REPO_ROOT}/skills/pr-review/scripts/filter-review-diff.sh"

FAILURES=0
TMPDIR=$(mktemp -d)
trap 'rm -rf "${TMPDIR}"' EXIT

# --- Test helpers ---

run_test() {
  local test_name="$1"
  local expected="$2"
  local actual="$3"

  if [[ "${actual}" == "${expected}" ]]; then
    echo "PASS: ${test_name}"
  else
    echo "FAIL: ${test_name}"
    echo "  expected: '${expected}'"
    echo "  actual:   '${actual}'"
    FAILURES=$((FAILURES + 1))
  fi
}

run_test_contains() {
  local test_name="$1"
  local needle="$2"
  local haystack="$3"

  if [[ "${haystack}" == *"${needle}"* ]]; then
    echo "PASS: ${test_name}"
  else
    echo "FAIL: ${test_name}"
    echo "  expected to contain: '${needle}'"
    echo "  actual:               '${haystack}'"
    FAILURES=$((FAILURES + 1))
  fi
}

run_test_not_contains() {
  local test_name="$1"
  local needle="$2"
  local haystack="$3"

  if [[ "${haystack}" != *"${needle}"* ]]; then
    echo "PASS: ${test_name}"
  else
    echo "FAIL: ${test_name}"
    echo "  expected NOT to contain: '${needle}'"
    echo "  actual:                   '${haystack}'"
    FAILURES=$((FAILURES + 1))
  fi
}

# --- Fixtures ---

NORMAL_DIFF='diff --git a/src/main.go b/src/main.go
index 1111111..2222222 100644
--- a/src/main.go
+++ b/src/main.go
@@ -1,4 +1,5 @@
 package main

+import "fmt"
 func main() {
 }'

LOCKFILE_SECTION='diff --git a/package-lock.json b/package-lock.json
index aaaaaaa..bbbbbbb 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -1,3 +1,3 @@
 {
-  "version": "1.0.0"
+  "version": "1.0.1"
 }'

CODE_SECTION='diff --git a/src/app.js b/src/app.js
index ccccccc..ddddddd 100644
--- a/src/app.js
+++ b/src/app.js
@@ -1,2 +1,3 @@
 function app() {
+  console.log("hi");
 }'

GENERATED_ADDED='diff --git a/gen/models.pb.go b/gen/models.pb.go
index 1111111..2222222 100644
--- a/gen/models.pb.go
+++ b/gen/models.pb.go
@@ -0,0 +1,3 @@
+// Code generated by protoc-gen-go. DO NOT EDIT.
+// @generated
+package gen'

GENERATED_REMOVED_ONLY='diff --git a/gen/legacy.pb.go b/gen/legacy.pb.go
index 1111111..2222222 100644
--- a/gen/legacy.pb.go
+++ b/gen/legacy.pb.go
@@ -1,2 +1,2 @@
-// @generated marker
-package gen
+package gen
+// no marker here'

MIGRATION_GENERATED='diff --git a/db/migrations/0001_init.sql b/db/migrations/0001_init.sql
index 1111111..2222222 100644
--- a/db/migrations/0001_init.sql
+++ b/db/migrations/0001_init.sql
@@ -0,0 +1,2 @@
+-- @generated by some tool
+CREATE TABLE foo (id INT);'

# shellcheck disable=SC2034 # read indirectly via ${!fixture_var} in the loop below
MINJS='diff --git a/dist/bundle.min.js b/dist/bundle.min.js
index 1111111..2222222 100644
--- a/dist/bundle.min.js
+++ b/dist/bundle.min.js
@@ -1 +1 @@
-old
+new'

# shellcheck disable=SC2034 # read indirectly via ${!fixture_var} in the loop below
SOURCEMAP='diff --git a/dist/bundle.js.map b/dist/bundle.js.map
index 1111111..2222222 100644
--- a/dist/bundle.js.map
+++ b/dist/bundle.js.map
@@ -1 +1 @@
-old
+new'

# shellcheck disable=SC2034 # read indirectly via ${!fixture_var} in the loop below
VENDORED='diff --git a/vendor/lib/thing.go b/vendor/lib/thing.go
index 1111111..2222222 100644
--- a/vendor/lib/thing.go
+++ b/vendor/lib/thing.go
@@ -1 +1 @@
-old
+new'

MALFORMED='This is not a diff.
Just some random text.
No file markers here.'

BINARY_VENDORED='diff --git a/vendor/blob.bin b/vendor/blob.bin
index 1111111..2222222 100644
Binary files a/vendor/blob.bin and b/vendor/blob.bin differ'

MODE_ONLY_VENDORED='diff --git a/vendor/tool.sh b/vendor/tool.sh
old mode 100644
new mode 100755'

QUOTED_VENDORED='diff --git "a/vendor/caf\303\251.min.js" "b/vendor/caf\303\251.min.js"
index 1111111..2222222 100644
--- "a/vendor/caf\303\251.min.js"
+++ "b/vendor/caf\303\251.min.js"
@@ -1 +1 @@
-old
+new'

NO_PATH_GENERATED='diff --git malformed-header-no-paths
@@ -0,0 +1,2 @@
+// @generated
+package gen'

REMIGRATIONS_LOCKFILE='diff --git a/db/remigrations/package-lock.json b/db/remigrations/package-lock.json
index aaaaaaa..bbbbbbb 100644
--- a/db/remigrations/package-lock.json
+++ b/db/remigrations/package-lock.json
@@ -1,3 +1,3 @@
 {
-  "version": "1.0.0"
+  "version": "1.0.1"
 }'

MIGRATIONS_LOCKFILE='diff --git a/db/migrations/package-lock.json b/db/migrations/package-lock.json
index aaaaaaa..bbbbbbb 100644
--- a/db/migrations/package-lock.json
+++ b/db/migrations/package-lock.json
@@ -1,3 +1,3 @@
 {
-  "version": "1.0.0"
+  "version": "1.0.1"
 }'

BINARY_SPACE_B='diff --git a/vendor/lib b/data.bin b/vendor/lib b/data.bin
index 1111111..2222222 100644
Binary files a/vendor/lib b/data.bin and b/vendor/lib b/data.bin differ'

QUOTED_RENAME_VENDORED='diff --git "a/src/caf\303\251.js" "b/vendor/caf\303\251.js"
similarity index 100%
rename from "src/caf\303\251.js"
rename to "vendor/caf\303\251.js"'

QUOTED_NEWLINE_VENDORED='diff --git "a/vendor/we\nird.js" "b/vendor/we\nird.js"
index 1111111..2222222 100644
--- "a/vendor/we\nird.js"
+++ "b/vendor/we\nird.js"
@@ -1 +1 @@
-old
+new'

# --- 1. Normal-code diff passes through byte-identical (the critical
#        transparency property: cmp, not just string equality). ---

printf '%s\n' "${NORMAL_DIFF}" > "${TMPDIR}/normal.in"
"${FILTER}" < "${TMPDIR}/normal.in" > "${TMPDIR}/normal.out"
if cmp -s "${TMPDIR}/normal.in" "${TMPDIR}/normal.out"; then
  echo "PASS: normal-diff-byte-identical"
else
  echo "FAIL: normal-diff-byte-identical"
  diff -u "${TMPDIR}/normal.in" "${TMPDIR}/normal.out" || true
  FAILURES=$((FAILURES + 1))
fi

# --- 2. Lockfile section stripped; mixed diff keeps the code section. ---

printf '%s\n%s\n' "${LOCKFILE_SECTION}" "${CODE_SECTION}" > "${TMPDIR}/mixed.in"
MIXED_OUT=$("${FILTER}" "${TMPDIR}/mixed.summary" < "${TMPDIR}/mixed.in")

run_test_not_contains "mixed-lockfile-not-in-stdout" "package-lock.json" "${MIXED_OUT}"
run_test_contains "mixed-code-section-kept" "console.log" "${MIXED_OUT}"
printf '%s\n' "${CODE_SECTION}" > "${TMPDIR}/mixed-code-expected"
CODE_ONLY=$(printf '%s\n' "${MIXED_OUT}")
if [[ "${CODE_ONLY}" == "${CODE_SECTION}" ]]; then
  echo "PASS: mixed-code-section-byte-identical"
else
  echo "FAIL: mixed-code-section-byte-identical"
  echo "  expected: ${CODE_SECTION}"
  echo "  actual:   ${CODE_ONLY}"
  FAILURES=$((FAILURES + 1))
fi

# --- 3. @generated in added lines strips; marker only in REMOVED lines
#        does not. ---

printf '%s\n' "${GENERATED_ADDED}" > "${TMPDIR}/gen-added.in"
GEN_ADDED_OUT=$("${FILTER}" "${TMPDIR}/gen-added.summary" < "${TMPDIR}/gen-added.in")
run_test "generated-added-strips-stdout" "" "${GEN_ADDED_OUT}"
run_test_contains "generated-added-in-summary" "gen/models.pb.go" "$(/bin/cat "${TMPDIR}/gen-added.summary")"
run_test_contains "generated-added-reason" "generated-marker" "$(/bin/cat "${TMPDIR}/gen-added.summary")"

printf '%s\n' "${GENERATED_REMOVED_ONLY}" > "${TMPDIR}/gen-removed.in"
"${FILTER}" "${TMPDIR}/gen-removed.summary" < "${TMPDIR}/gen-removed.in" > "${TMPDIR}/gen-removed.out"
if cmp -s "${TMPDIR}/gen-removed.in" "${TMPDIR}/gen-removed.out"; then
  echo "PASS: generated-marker-in-removed-line-does-not-strip"
else
  echo "FAIL: generated-marker-in-removed-line-does-not-strip"
  diff -u "${TMPDIR}/gen-removed.in" "${TMPDIR}/gen-removed.out" || true
  FAILURES=$((FAILURES + 1))
fi
run_test "generated-removed-empty-summary" "" "$(/bin/cat "${TMPDIR}/gen-removed.summary" 2>/dev/null || true)"

# --- 4. Migration file with @generated is KEPT (exemption beats every
#        strip rule, including the generated-marker rule). ---

printf '%s\n' "${MIGRATION_GENERATED}" > "${TMPDIR}/migration.in"
"${FILTER}" "${TMPDIR}/migration.summary" < "${TMPDIR}/migration.in" > "${TMPDIR}/migration.out"
if cmp -s "${TMPDIR}/migration.in" "${TMPDIR}/migration.out"; then
  echo "PASS: migration-with-generated-marker-kept"
else
  echo "FAIL: migration-with-generated-marker-kept"
  diff -u "${TMPDIR}/migration.in" "${TMPDIR}/migration.out" || true
  FAILURES=$((FAILURES + 1))
fi
run_test "migration-not-in-summary" "" "$(/bin/cat "${TMPDIR}/migration.summary" 2>/dev/null || true)"

# --- 5. *.min.js, *.map, vendor/ stripped. ---

for case in "MINJS:minjs:bundle.min.js:minified" "SOURCEMAP:sourcemap:bundle.js.map:sourcemap" "VENDORED:vendored:vendor/lib/thing.go:vendored"; do
  fixture_var="${case%%:*}"
  rest="${case#*:}"
  label="${rest%%:*}"
  rest="${rest#*:}"
  path_hint="${rest%%:*}"
  reason="${rest#*:}"
  fixture="${!fixture_var}"

  printf '%s\n' "${fixture}" > "${TMPDIR}/${label}.in"
  OUT=$("${FILTER}" "${TMPDIR}/${label}.summary" < "${TMPDIR}/${label}.in")
  run_test "${label}-stdout-empty" "" "${OUT}"
  run_test_contains "${label}-in-summary" "${path_hint}" "$(/bin/cat "${TMPDIR}/${label}.summary")"
  run_test_contains "${label}-reason-recorded" "${reason}" "$(/bin/cat "${TMPDIR}/${label}.summary")"
done

# --- 6. Summary lines correct (path, counts, reason); summary never on
#        stdout. ---

SUMMARY_LINE=$(/bin/cat "${TMPDIR}/mixed.summary")
run_test "summary-line-format" "package-lock.json  +1/-1  lockfile" "${SUMMARY_LINE}"
run_test_not_contains "summary-never-on-stdout" "lockfile" "${MIXED_OUT}"

# --- 7. Empty result (everything stripped) produces empty stdout + full
#        summary, exit 0. ---

printf '%s\n' "${LOCKFILE_SECTION}" > "${TMPDIR}/all-stripped.in"
set +e
ALL_STRIPPED_OUT=$("${FILTER}" "${TMPDIR}/all-stripped.summary" < "${TMPDIR}/all-stripped.in")
ALL_STRIPPED_EXIT=$?
set -e
run_test "all-stripped-exit-0" "0" "${ALL_STRIPPED_EXIT}"
run_test "all-stripped-stdout-empty" "" "${ALL_STRIPPED_OUT}"
run_test_contains "all-stripped-summary-full" "package-lock.json" "$(/bin/cat "${TMPDIR}/all-stripped.summary")"

# --- 8. Malformed input (not a diff) passes through unchanged, exit 0. ---

printf '%s\n' "${MALFORMED}" > "${TMPDIR}/malformed.in"
set +e
"${FILTER}" < "${TMPDIR}/malformed.in" > "${TMPDIR}/malformed.out"
MALFORMED_EXIT=$?
set -e
run_test "malformed-exit-0" "0" "${MALFORMED_EXIT}"
if cmp -s "${TMPDIR}/malformed.in" "${TMPDIR}/malformed.out"; then
  echo "PASS: malformed-input-passthrough"
else
  echo "FAIL: malformed-input-passthrough"
  diff -u "${TMPDIR}/malformed.in" "${TMPDIR}/malformed.out" || true
  FAILURES=$((FAILURES + 1))
fi

# --- 9. Stale summary file is truncated: a run with no exclusions must
#        leave the caller-supplied summary empty, not a prior run's
#        contents. ---

printf 'stale/path.js  +9/-9  lockfile\n' > "${TMPDIR}/stale.summary"
printf '%s\n' "${NORMAL_DIFF}" > "${TMPDIR}/stale.in"
"${FILTER}" "${TMPDIR}/stale.summary" < "${TMPDIR}/stale.in" > /dev/null
run_test "stale-summary-truncated" "" "$(/bin/cat "${TMPDIR}/stale.summary")"

# --- 10. Binary and mode-only sections have no ---/+++ headers; the
#         path must come from the `diff --git` header itself. ---

printf '%s\n' "${BINARY_VENDORED}" > "${TMPDIR}/binary.in"
BINARY_OUT=$("${FILTER}" "${TMPDIR}/binary.summary" < "${TMPDIR}/binary.in")
run_test "binary-vendored-stdout-empty" "" "${BINARY_OUT}"
run_test_contains "binary-vendored-in-summary" "vendor/blob.bin" "$(/bin/cat "${TMPDIR}/binary.summary")"

printf '%s\n' "${MODE_ONLY_VENDORED}" > "${TMPDIR}/mode-only.in"
MODE_ONLY_OUT=$("${FILTER}" "${TMPDIR}/mode-only.summary" < "${TMPDIR}/mode-only.in")
run_test "mode-only-vendored-stdout-empty" "" "${MODE_ONLY_OUT}"
run_test_contains "mode-only-vendored-in-summary" "vendor/tool.sh" "$(/bin/cat "${TMPDIR}/mode-only.summary")"

# --- 11. Git-quoted paths are dequoted before classification. ---

printf '%s\n' "${QUOTED_VENDORED}" > "${TMPDIR}/quoted.in"
QUOTED_OUT=$("${FILTER}" "${TMPDIR}/quoted.summary" < "${TMPDIR}/quoted.in")
run_test "quoted-path-stdout-empty" "" "${QUOTED_OUT}"
run_test_contains "quoted-path-in-summary" "vendor/caf" "$(/bin/cat "${TMPDIR}/quoted.summary")"
run_test_contains "quoted-path-reason-recorded" "minified" "$(/bin/cat "${TMPDIR}/quoted.summary")"
run_test_contains "quoted-path-octal-decoded" "vendor/café.min.js" "$(/bin/cat "${TMPDIR}/quoted.summary")"

# --- 12. Fail-open: a section with a hunk and an @generated added line
#         but no parseable path anywhere passes through unchanged, with
#         no summary record. ---

printf '%s\n' "${NO_PATH_GENERATED}" > "${TMPDIR}/no-path.in"
"${FILTER}" "${TMPDIR}/no-path.summary" < "${TMPDIR}/no-path.in" > "${TMPDIR}/no-path.out"
if cmp -s "${TMPDIR}/no-path.in" "${TMPDIR}/no-path.out"; then
  echo "PASS: no-parseable-path-fails-open"
else
  echo "FAIL: no-parseable-path-fails-open"
  diff -u "${TMPDIR}/no-path.in" "${TMPDIR}/no-path.out" || true
  FAILURES=$((FAILURES + 1))
fi
run_test "no-parseable-path-empty-summary" "" "$(/bin/cat "${TMPDIR}/no-path.summary" 2>/dev/null || true)"

# --- 13. Migration exemption matches whole path components only:
#         db/remigrations/ is NOT exempt, db/migrations/ is (even for a
#         lockfile name). ---

printf '%s\n' "${REMIGRATIONS_LOCKFILE}" > "${TMPDIR}/remigrations.in"
REMIG_OUT=$("${FILTER}" "${TMPDIR}/remigrations.summary" < "${TMPDIR}/remigrations.in")
run_test "remigrations-not-exempt-stdout-empty" "" "${REMIG_OUT}"
run_test_contains "remigrations-in-summary" "db/remigrations/package-lock.json" "$(/bin/cat "${TMPDIR}/remigrations.summary")"

printf '%s\n' "${MIGRATIONS_LOCKFILE}" > "${TMPDIR}/migrations-lock.in"
"${FILTER}" "${TMPDIR}/migrations-lock.summary" < "${TMPDIR}/migrations-lock.in" > "${TMPDIR}/migrations-lock.out"
if cmp -s "${TMPDIR}/migrations-lock.in" "${TMPDIR}/migrations-lock.out"; then
  echo "PASS: migrations-component-exempt"
else
  echo "FAIL: migrations-component-exempt"
  diff -u "${TMPDIR}/migrations-lock.in" "${TMPDIR}/migrations-lock.out" || true
  FAILURES=$((FAILURES + 1))
fi
run_test "migrations-lockfile-empty-summary" "" "$(/bin/cat "${TMPDIR}/migrations-lock.summary" 2>/dev/null || true)"

# --- 14. Pending-state buffering is bounded: a deletion-heavy section
#         resolves keep at the buffer cap, so an @generated added line
#         arriving after 100+ buffered lines no longer strips and the
#         section streams through unchanged. ---

{
  echo 'diff --git a/dist/big.js b/dist/big.js'
  echo 'index 1111111..2222222 100644'
  echo '--- a/dist/big.js'
  echo '+++ b/dist/big.js'
  echo '@@ -1,150 +1,2 @@'
  for i in $(seq 1 150); do echo "-deleted line ${i}"; done
  echo '+// @generated'
  echo '+var big = 1'
} > "${TMPDIR}/deletion.in"
"${FILTER}" "${TMPDIR}/deletion.summary" < "${TMPDIR}/deletion.in" > "${TMPDIR}/deletion.out"
if cmp -s "${TMPDIR}/deletion.in" "${TMPDIR}/deletion.out"; then
  echo "PASS: deletion-heavy-section-bounded-keep"
else
  echo "FAIL: deletion-heavy-section-bounded-keep"
  diff -u "${TMPDIR}/deletion.in" "${TMPDIR}/deletion.out" || true
  FAILURES=$((FAILURES + 1))
fi
run_test "deletion-heavy-empty-summary" "" "$(/bin/cat "${TMPDIR}/deletion.summary" 2>/dev/null || true)"

# --- 15. A path itself containing " b/" splits at the position where
#         both header sides name the same file, not at the last " b/"
#         marker. ---

printf '%s\n' "${BINARY_SPACE_B}" > "${TMPDIR}/space-b.in"
SPACE_B_OUT=$("${FILTER}" "${TMPDIR}/space-b.summary" < "${TMPDIR}/space-b.in")
run_test "space-b-path-stdout-empty" "" "${SPACE_B_OUT}"
run_test_contains "space-b-path-in-summary" "vendor/lib b/data.bin" "$(/bin/cat "${TMPDIR}/space-b.summary")"

# --- 16. Quoted rename from/to metadata is dequoted before
#         classification: a rename into vendor/ is stripped. ---

printf '%s\n' "${QUOTED_RENAME_VENDORED}" > "${TMPDIR}/quoted-rename.in"
QUOTED_RENAME_OUT=$("${FILTER}" "${TMPDIR}/quoted-rename.summary" < "${TMPDIR}/quoted-rename.in")
run_test "quoted-rename-stdout-empty" "" "${QUOTED_RENAME_OUT}"
run_test_contains "quoted-rename-in-summary" "vendor/caf" "$(/bin/cat "${TMPDIR}/quoted-rename.summary")"
run_test_contains "quoted-rename-reason-recorded" "vendored" "$(/bin/cat "${TMPDIR}/quoted-rename.summary")"

# --- 17. A \n escape in a quoted path stays a literal backslash
#         sequence: the file still classifies by path shape and its
#         summary record is exactly one physical line. ---

printf '%s\n' "${QUOTED_NEWLINE_VENDORED}" > "${TMPDIR}/quoted-nl.in"
QUOTED_NL_OUT=$("${FILTER}" "${TMPDIR}/quoted-nl.summary" < "${TMPDIR}/quoted-nl.in")
run_test "quoted-newline-stdout-empty" "" "${QUOTED_NL_OUT}"
run_test_contains "quoted-newline-reason-recorded" "vendored" "$(/bin/cat "${TMPDIR}/quoted-nl.summary")"
run_test "quoted-newline-single-summary-line" "1" "$(wc -l < "${TMPDIR}/quoted-nl.summary" | tr -d ' ')"

# --- 18. A generated marker on a NON-generated-looking path never
#         strips: an author-planted @generated cannot hide an ordinary
#         source file from review. ---

MARKER_ON_SOURCE='diff --git a/src/main.go b/src/main.go
index 1111111..2222222 100644
--- a/src/main.go
+++ b/src/main.go
@@ -1,3 +1,4 @@
 package main
+// @generated — but this file is hand-written
 func main() {
 }'

printf '%s\n' "${MARKER_ON_SOURCE}" > "${TMPDIR}/marker-src.in"
"${FILTER}" "${TMPDIR}/marker-src.summary" < "${TMPDIR}/marker-src.in" > "${TMPDIR}/marker-src.out"
if cmp -s "${TMPDIR}/marker-src.in" "${TMPDIR}/marker-src.out"; then
  echo "PASS: marker-on-source-path-kept"
else
  echo "FAIL: marker-on-source-path-kept"
  diff -u "${TMPDIR}/marker-src.in" "${TMPDIR}/marker-src.out" || true
  FAILURES=$((FAILURES + 1))
fi
run_test "marker-on-source-path-empty-summary" "" "$(/bin/cat "${TMPDIR}/marker-src.summary" 2>/dev/null || true)"

# --- 19. A modified .pb.go carries the Go generated marker as a CONTEXT
#         line, not an added line — it must still strip. ---

PBGO_CONTEXT_MARKER='diff --git a/api/service.pb.go b/api/service.pb.go
index 1111111..2222222 100644
--- a/api/service.pb.go
+++ b/api/service.pb.go
@@ -10,7 +10,7 @@
 // Code generated by protoc-gen-go. DO NOT EDIT.
 package api
-const foo = 1
+const foo = 2
 var bar = 3'

printf '%s\n' "${PBGO_CONTEXT_MARKER}" > "${TMPDIR}/pbgo-ctx.in"
PBGO_CTX_OUT=$("${FILTER}" "${TMPDIR}/pbgo-ctx.summary" < "${TMPDIR}/pbgo-ctx.in")
run_test "pbgo-context-marker-stdout-empty" "" "${PBGO_CTX_OUT}"
run_test_contains "pbgo-context-marker-in-summary" "api/service.pb.go" "$(/bin/cat "${TMPDIR}/pbgo-ctx.summary")"
run_test_contains "pbgo-context-marker-reason" "generated-marker" "$(/bin/cat "${TMPDIR}/pbgo-ctx.summary")"

# --- 20. Paths with spaces: git tab-terminates the ---/+++ path, so the
#         tab must be stripped for $-anchored rules to match. ---

{
  printf 'diff --git a/lib x/foo.min.js b/lib x/foo.min.js\n'
  printf 'index 1111111..2222222 100644\n'
  printf -- '--- a/lib x/foo.min.js\t\n'
  printf '+++ b/lib x/foo.min.js\t\n'
  printf '@@ -1 +1 @@\n-old\n+new\n'
} > "${TMPDIR}/tab-min.in"
TAB_MIN_OUT=$("${FILTER}" "${TMPDIR}/tab-min.summary" < "${TMPDIR}/tab-min.in")
run_test "tab-path-minified-stdout-empty" "" "${TAB_MIN_OUT}"
run_test_contains "tab-path-minified-in-summary" "lib x/foo.min.js" "$(/bin/cat "${TMPDIR}/tab-min.summary")"
run_test_contains "tab-path-minified-reason" "minified" "$(/bin/cat "${TMPDIR}/tab-min.summary")"

{
  printf 'diff --git a/pkg dir/package-lock.json b/pkg dir/package-lock.json\n'
  printf 'index 1111111..2222222 100644\n'
  printf -- '--- a/pkg dir/package-lock.json\t\n'
  printf '+++ b/pkg dir/package-lock.json\t\n'
  printf '@@ -1 +1 @@\n-old\n+new\n'
} > "${TMPDIR}/tab-lock.in"
TAB_LOCK_OUT=$("${FILTER}" "${TMPDIR}/tab-lock.summary" < "${TMPDIR}/tab-lock.in")
run_test "tab-path-lockfile-stdout-empty" "" "${TAB_LOCK_OUT}"
run_test_contains "tab-path-lockfile-in-summary" "pkg dir/package-lock.json" "$(/bin/cat "${TMPDIR}/tab-lock.summary")"
run_test_contains "tab-path-lockfile-reason" "lockfile" "$(/bin/cat "${TMPDIR}/tab-lock.summary")"

# --- 21. GitLab-shaped diff (no `diff --git` lines; sections start at
#         `--- a/X`): filtering still applies, kept sections stream
#         through byte-identical. ---

GITLAB_KEPT_SECTION='--- a/src/app.js
+++ b/src/app.js
@@ -1,2 +1,3 @@
 function app() {
+  console.log("hi");
 }'

GITLAB_DIFF='--- a/package-lock.json
+++ b/package-lock.json
@@ -1,3 +1,3 @@
 {
-  "version": "1.0.0"
+  "version": "1.0.1"
 }
'"${GITLAB_KEPT_SECTION}"

printf '%s\n' "${GITLAB_DIFF}" > "${TMPDIR}/gitlab.in"
GITLAB_OUT=$("${FILTER}" "${TMPDIR}/gitlab.summary" < "${TMPDIR}/gitlab.in")
run_test_not_contains "gitlab-lockfile-not-in-stdout" "package-lock.json" "${GITLAB_OUT}"
run_test "gitlab-kept-section-byte-identical" "${GITLAB_KEPT_SECTION}" "${GITLAB_OUT}"
run_test_contains "gitlab-lockfile-in-summary" "package-lock.json" "$(/bin/cat "${TMPDIR}/gitlab.summary")"
run_test_contains "gitlab-lockfile-reason" "lockfile" "$(/bin/cat "${TMPDIR}/gitlab.summary")"

# --- 22. A REMOVED content line whose original text begins "-- a/..."
#         renders as `--- a/...` — it must NOT be taken for a GitLab
#         section boundary (a real boundary is `--- ` immediately
#         followed by `+++ `). The section passes through intact with
#         no false exclusion. ---

GITLAB_FAKE_BOUNDARY='--- a/src/real.js
+++ b/src/real.js
@@ -1,4 +1,3 @@
 function real() {
--- a/vendor/fake.js
-  var y = 2
+  var z = 3
 }
@@ -10,2 +9,2 @@
 more()
-old()
+new()'

printf '%s\n' "${GITLAB_FAKE_BOUNDARY}" > "${TMPDIR}/gitlab-fake.in"
"${FILTER}" "${TMPDIR}/gitlab-fake.summary" < "${TMPDIR}/gitlab-fake.in" > "${TMPDIR}/gitlab-fake.out"
if cmp -s "${TMPDIR}/gitlab-fake.in" "${TMPDIR}/gitlab-fake.out"; then
  echo "PASS: gitlab-fake-boundary-passthrough"
else
  echo "FAIL: gitlab-fake-boundary-passthrough"
  diff -u "${TMPDIR}/gitlab-fake.in" "${TMPDIR}/gitlab-fake.out" || true
  FAILURES=$((FAILURES + 1))
fi
run_test "gitlab-fake-boundary-empty-summary" "" "$(/bin/cat "${TMPDIR}/gitlab-fake.summary" 2>/dev/null || true)"

# --- Wrap up ---

echo ""
if [ "${FAILURES}" -gt 0 ]; then
  echo "${FAILURES} test(s) failed"
  exit 1
fi
echo "All tests passed"
