#!/usr/bin/env bash
# filter-review-diff-test.sh — Tests for
# skills/pr-review/scripts/filter-review-diff.sh
#
# Run from the repo root:
#   bash scripts/filter-review-diff-test.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FILTER="${REPO_ROOT}/skills/pr-review/scripts/filter-review-diff.sh"

FAILURES=0
TMPDIR=$(mktemp -d)
trap 'rm -rf "${TMPDIR}"' EXIT

# --- Test helpers ---

run_test() {
  local test_name="$1"
  local expected="$2"
  local actual="$3"

  if [[ "${actual}" == "${expected}" ]]; then
    echo "PASS: ${test_name}"
  else
    echo "FAIL: ${test_name}"
    echo "  expected: '${expected}'"
    echo "  actual:   '${actual}'"
    FAILURES=$((FAILURES + 1))
  fi
}

run_test_contains() {
  local test_name="$1"
  local needle="$2"
  local haystack="$3"

  if [[ "${haystack}" == *"${needle}"* ]]; then
    echo "PASS: ${test_name}"
  else
    echo "FAIL: ${test_name}"
    echo "  expected to contain: '${needle}'"
    echo "  actual:               '${haystack}'"
    FAILURES=$((FAILURES + 1))
  fi
}

run_test_not_contains() {
  local test_name="$1"
  local needle="$2"
  local haystack="$3"

  if [[ "${haystack}" != *"${needle}"* ]]; then
    echo "PASS: ${test_name}"
  else
    echo "FAIL: ${test_name}"
    echo "  expected NOT to contain: '${needle}'"
    echo "  actual:                   '${haystack}'"
    FAILURES=$((FAILURES + 1))
  fi
}

# --- Fixtures ---

NORMAL_DIFF='diff --git a/src/main.go b/src/main.go
index 1111111..2222222 100644
--- a/src/main.go
+++ b/src/main.go
@@ -1,4 +1,5 @@
 package main

+import "fmt"
 func main() {
 }'

LOCKFILE_SECTION='diff --git a/package-lock.json b/package-lock.json
index aaaaaaa..bbbbbbb 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -1,3 +1,3 @@
 {
-  "version": "1.0.0"
+  "version": "1.0.1"
 }'

CODE_SECTION='diff --git a/src/app.js b/src/app.js
index ccccccc..ddddddd 100644
--- a/src/app.js
+++ b/src/app.js
@@ -1,2 +1,3 @@
 function app() {
+  console.log("hi");
 }'

GENERATED_ADDED='diff --git a/gen/models.go b/gen/models.go
index 1111111..2222222 100644
--- a/gen/models.go
+++ b/gen/models.go
@@ -0,0 +1,3 @@
+// Code generated by protoc-gen-go. DO NOT EDIT.
+// @generated
+package gen'

GENERATED_REMOVED_ONLY='diff --git a/gen/legacy.go b/gen/legacy.go
index 1111111..2222222 100644
--- a/gen/legacy.go
+++ b/gen/legacy.go
@@ -1,2 +1,2 @@
-// @generated marker
-package gen
+package gen
+// no marker here'

MIGRATION_GENERATED='diff --git a/db/migrations/0001_init.sql b/db/migrations/0001_init.sql
index 1111111..2222222 100644
--- a/db/migrations/0001_init.sql
+++ b/db/migrations/0001_init.sql
@@ -0,0 +1,2 @@
+-- @generated by some tool
+CREATE TABLE foo (id INT);'

# shellcheck disable=SC2034 # read indirectly via ${!fixture_var} in the loop below
MINJS='diff --git a/dist/bundle.min.js b/dist/bundle.min.js
index 1111111..2222222 100644
--- a/dist/bundle.min.js
+++ b/dist/bundle.min.js
@@ -1 +1 @@
-old
+new'

# shellcheck disable=SC2034 # read indirectly via ${!fixture_var} in the loop below
SOURCEMAP='diff --git a/dist/bundle.js.map b/dist/bundle.js.map
index 1111111..2222222 100644
--- a/dist/bundle.js.map
+++ b/dist/bundle.js.map
@@ -1 +1 @@
-old
+new'

# shellcheck disable=SC2034 # read indirectly via ${!fixture_var} in the loop below
VENDORED='diff --git a/vendor/lib/thing.go b/vendor/lib/thing.go
index 1111111..2222222 100644
--- a/vendor/lib/thing.go
+++ b/vendor/lib/thing.go
@@ -1 +1 @@
-old
+new'

MALFORMED='This is not a diff.
Just some random text.
No file markers here.'

# --- 1. Normal-code diff passes through byte-identical (the critical
#        transparency property: cmp, not just string equality). ---

printf '%s\n' "${NORMAL_DIFF}" > "${TMPDIR}/normal.in"
"${FILTER}" < "${TMPDIR}/normal.in" > "${TMPDIR}/normal.out"
if cmp -s "${TMPDIR}/normal.in" "${TMPDIR}/normal.out"; then
  echo "PASS: normal-diff-byte-identical"
else
  echo "FAIL: normal-diff-byte-identical"
  diff -u "${TMPDIR}/normal.in" "${TMPDIR}/normal.out" || true
  FAILURES=$((FAILURES + 1))
fi

# --- 2. Lockfile section stripped; mixed diff keeps the code section. ---

printf '%s\n%s\n' "${LOCKFILE_SECTION}" "${CODE_SECTION}" > "${TMPDIR}/mixed.in"
MIXED_OUT=$("${FILTER}" "${TMPDIR}/mixed.summary" < "${TMPDIR}/mixed.in")

run_test_not_contains "mixed-lockfile-not-in-stdout" "package-lock.json" "${MIXED_OUT}"
run_test_contains "mixed-code-section-kept" "console.log" "${MIXED_OUT}"
printf '%s\n' "${CODE_SECTION}" > "${TMPDIR}/mixed-code-expected"
CODE_ONLY=$(printf '%s\n' "${MIXED_OUT}")
if [[ "${CODE_ONLY}" == "${CODE_SECTION}" ]]; then
  echo "PASS: mixed-code-section-byte-identical"
else
  echo "FAIL: mixed-code-section-byte-identical"
  echo "  expected: ${CODE_SECTION}"
  echo "  actual:   ${CODE_ONLY}"
  FAILURES=$((FAILURES + 1))
fi

# --- 3. @generated in added lines strips; marker only in REMOVED lines
#        does not. ---

printf '%s\n' "${GENERATED_ADDED}" > "${TMPDIR}/gen-added.in"
GEN_ADDED_OUT=$("${FILTER}" "${TMPDIR}/gen-added.summary" < "${TMPDIR}/gen-added.in")
run_test "generated-added-strips-stdout" "" "${GEN_ADDED_OUT}"
run_test_contains "generated-added-in-summary" "gen/models.go" "$(/bin/cat "${TMPDIR}/gen-added.summary")"
run_test_contains "generated-added-reason" "generated-marker" "$(/bin/cat "${TMPDIR}/gen-added.summary")"

printf '%s\n' "${GENERATED_REMOVED_ONLY}" > "${TMPDIR}/gen-removed.in"
"${FILTER}" "${TMPDIR}/gen-removed.summary" < "${TMPDIR}/gen-removed.in" > "${TMPDIR}/gen-removed.out"
if cmp -s "${TMPDIR}/gen-removed.in" "${TMPDIR}/gen-removed.out"; then
  echo "PASS: generated-marker-in-removed-line-does-not-strip"
else
  echo "FAIL: generated-marker-in-removed-line-does-not-strip"
  diff -u "${TMPDIR}/gen-removed.in" "${TMPDIR}/gen-removed.out" || true
  FAILURES=$((FAILURES + 1))
fi
run_test "generated-removed-empty-summary" "" "$(/bin/cat "${TMPDIR}/gen-removed.summary" 2>/dev/null || true)"

# --- 4. Migration file with @generated is KEPT (exemption beats every
#        strip rule, including the generated-marker rule). ---

printf '%s\n' "${MIGRATION_GENERATED}" > "${TMPDIR}/migration.in"
"${FILTER}" "${TMPDIR}/migration.summary" < "${TMPDIR}/migration.in" > "${TMPDIR}/migration.out"
if cmp -s "${TMPDIR}/migration.in" "${TMPDIR}/migration.out"; then
  echo "PASS: migration-with-generated-marker-kept"
else
  echo "FAIL: migration-with-generated-marker-kept"
  diff -u "${TMPDIR}/migration.in" "${TMPDIR}/migration.out" || true
  FAILURES=$((FAILURES + 1))
fi
run_test "migration-not-in-summary" "" "$(/bin/cat "${TMPDIR}/migration.summary" 2>/dev/null || true)"

# --- 5. *.min.js, *.map, vendor/ stripped. ---

for case in "MINJS:minjs:bundle.min.js:minified" "SOURCEMAP:sourcemap:bundle.js.map:sourcemap" "VENDORED:vendored:vendor/lib/thing.go:vendored"; do
  fixture_var="${case%%:*}"
  rest="${case#*:}"
  label="${rest%%:*}"
  rest="${rest#*:}"
  path_hint="${rest%%:*}"
  reason="${rest#*:}"
  fixture="${!fixture_var}"

  printf '%s\n' "${fixture}" > "${TMPDIR}/${label}.in"
  OUT=$("${FILTER}" "${TMPDIR}/${label}.summary" < "${TMPDIR}/${label}.in")
  run_test "${label}-stdout-empty" "" "${OUT}"
  run_test_contains "${label}-in-summary" "${path_hint}" "$(/bin/cat "${TMPDIR}/${label}.summary")"
  run_test_contains "${label}-reason-recorded" "${reason}" "$(/bin/cat "${TMPDIR}/${label}.summary")"
done

# --- 6. Summary lines correct (path, counts, reason); summary never on
#        stdout. ---

SUMMARY_LINE=$(/bin/cat "${TMPDIR}/mixed.summary")
run_test "summary-line-format" "package-lock.json  +1/-1  lockfile" "${SUMMARY_LINE}"
run_test_not_contains "summary-never-on-stdout" "lockfile" "${MIXED_OUT}"

# --- 7. Empty result (everything stripped) produces empty stdout + full
#        summary, exit 0. ---

printf '%s\n' "${LOCKFILE_SECTION}" > "${TMPDIR}/all-stripped.in"
set +e
ALL_STRIPPED_OUT=$("${FILTER}" "${TMPDIR}/all-stripped.summary" < "${TMPDIR}/all-stripped.in")
ALL_STRIPPED_EXIT=$?
set -e
run_test "all-stripped-exit-0" "0" "${ALL_STRIPPED_EXIT}"
run_test "all-stripped-stdout-empty" "" "${ALL_STRIPPED_OUT}"
run_test_contains "all-stripped-summary-full" "package-lock.json" "$(/bin/cat "${TMPDIR}/all-stripped.summary")"

# --- 8. Malformed input (not a diff) passes through unchanged, exit 0. ---

printf '%s\n' "${MALFORMED}" > "${TMPDIR}/malformed.in"
set +e
"${FILTER}" < "${TMPDIR}/malformed.in" > "${TMPDIR}/malformed.out"
MALFORMED_EXIT=$?
set -e
run_test "malformed-exit-0" "0" "${MALFORMED_EXIT}"
if cmp -s "${TMPDIR}/malformed.in" "${TMPDIR}/malformed.out"; then
  echo "PASS: malformed-input-passthrough"
else
  echo "FAIL: malformed-input-passthrough"
  diff -u "${TMPDIR}/malformed.in" "${TMPDIR}/malformed.out" || true
  FAILURES=$((FAILURES + 1))
fi

# --- Wrap up ---

echo ""
if [ "${FAILURES}" -gt 0 ]; then
  echo "${FAILURES} test(s) failed"
  exit 1
fi
echo "All tests passed"
