#!/usr/bin/env bash
# post-link-check.sh — turn the link-check agent's JSON result into one comment.
#
# Generated by `fullsend agent new`. Safe to edit.
#
# Runs on the trusted runner after the sandbox exits. The working directory is
# the run's iteration directory, so the agent output is ./output/agent-result.json.
#
# Required env:
#   ISSUE_URL — HTML URL of the work item (the harness maps GITHUB_ISSUE_URL to it)
#   GH_TOKEN  — minted by fullsend from the harness `role:` field
#
# Treat the result file as untrusted: it is model output. Only the three
# fields below are ever read, each is required to be a string, and the
# comment body is piped on stdin rather than interpolated into a command.

set -euo pipefail

: "${ISSUE_URL:?ISSUE_URL must be set}"
: "${GH_TOKEN:?GH_TOKEN must be set}"

RESULT_FILE="output/agent-result.json"
MARKER="<!-- fullsend:link-check-agent -->"
MAX_SUMMARY_CHARS=200
MAX_COMMENT_CHARS=16384

if [[ ! -f "${RESULT_FILE}" ]]; then
  echo "post-link-check: ${RESULT_FILE} not found" >&2
  exit 1
fi
if ! jq -e . "${RESULT_FILE}" >/dev/null 2>&1; then
  echo "post-link-check: ${RESULT_FILE} is not valid JSON" >&2
  exit 1
fi

# Field allowlist: anything else in the file is ignored by construction.
status=$(jq -r 'if (.status | type) == "string" then .status else empty end' "${RESULT_FILE}")
summary=$(jq -r 'if (.summary | type) == "string" then .summary else empty end' "${RESULT_FILE}")
comment=$(jq -r 'if (.comment | type) == "string" then .comment else empty end' "${RESULT_FILE}")

case "${status}" in
  ok|findings|error) ;;
  *) echo "post-link-check: status must be ok, findings or error (got '${status}')" >&2; exit 1 ;;
esac
[[ -n "${summary}" ]] || { echo "post-link-check: summary is required" >&2; exit 1; }
[[ -n "${comment}" ]] || { echo "post-link-check: comment is required" >&2; exit 1; }
if (( ${#summary} > MAX_SUMMARY_CHARS )); then
  echo "post-link-check: summary exceeds ${MAX_SUMMARY_CHARS} characters" >&2
  exit 1
fi
if (( ${#comment} > MAX_COMMENT_CHARS )); then
  comment="${comment:0:${MAX_COMMENT_CHARS}}"$'\n\n_(truncated)_'
fi

if [[ "${status}" == "ok" ]]; then
  echo "post-link-check: status=ok, nothing to post" >&2
  exit 0
fi

# Derive the repo and number from the work item URL rather than trusting extra
# environment. The pattern also rejects anything that is not a github.com URL.
url_re='^https://github[.]com/([A-Za-z0-9._-]+/[A-Za-z0-9._-]+)/(issues|pull)/([0-9]+)$'
if [[ ! "${ISSUE_URL}" =~ ${url_re} ]]; then
  echo "post-link-check: ISSUE_URL is not a GitHub issue or pull request URL" >&2
  exit 1
fi
REPO="${BASH_REMATCH[1]}"
NUMBER="${BASH_REMATCH[3]}"

if [[ "${POST_LINK_CHECK_DRY_RUN:-}" == "1" ]]; then
  printf '**%s**\n\n%s\n' "${summary}" "${comment}"
  echo "post-link-check: dry run, not posting" >&2
  exit 0
fi

# fullsend issues post-comment is the repo's sticky-comment primitive: it
# finds this agent's previous comment by marker and edits it in place, so
# re-runs do not flood the work item.
printf '**%s**\n\n%s\n' "${summary}" "${comment}" \
  | fullsend issues post-comment \
      --tracker github \
      --project "${REPO}" \
      --number "${NUMBER}" \
      --marker "${MARKER}" \
      --result -
